-- Add STORE_MANAGER and STORE_OPERATOR to user_roles.name (user_roles_name enum)
ALTER TABLE `user_roles` MODIFY `name` ENUM('ADMIN', 'SELLER', 'STORE_MANAGER', 'STORE_OPERATOR', 'USER', 'DELIVERY_EXECUTIVE', 'DELIVERY_MANAGER', 'DELIVERY_PARTNER', 'PARTNER_MANAGER', 'CEO', 'CFO') NOT NULL;
